/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2017 (14.0.2047)
    Source Database Engine Edition : Microsoft SQL Server Express Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2017
    Target Database Engine Edition : Microsoft SQL Server Express Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [RPA]    Script Date: 2023/05/22 11:30:16 AM ******/
CREATE DATABASE [RPA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RPA', FILENAME = N'C:\Data\RPA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RPA_log', FILENAME = N'C:\Data\RPA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [RPA] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RPA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RPA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RPA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RPA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RPA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RPA] SET ARITHABORT OFF 
GO

ALTER DATABASE [RPA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RPA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RPA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RPA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RPA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RPA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RPA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RPA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RPA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RPA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RPA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RPA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RPA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RPA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RPA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RPA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RPA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RPA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RPA] SET  MULTI_USER 
GO

ALTER DATABASE [RPA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RPA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RPA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RPA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RPA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RPA] SET QUERY_STORE = OFF
GO

USE [RPA]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [RPA] SET  READ_WRITE 
GO


